FROM docker.io/library/debian:trixie

# https://docs.docker.com/build/cache/optimize/#use-cache-mounts
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    rm -v /etc/apt/apt.conf.d/docker-clean && \
    sed -E -i -e 's/^(Types:.*deb)/\1 deb-src/' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install --no-install-recommends podman docker-cli curl git ca-certificates && \
    apt-get -y build-dep --no-install-recommends emacs-nox

ARG cask_commit=550bbeb2687b015317da48c35e7289a957830135
RUN git clone --single-branch https://github.com/cask/cask.git /cask && \
    (cd /cask && git checkout ${cask_commit})

ARG emacs_release=30.1
# TODO gpg verification
RUN --mount=type=cache,target=/tmp/ftp,sharing=locked \
    cd /tmp/ftp && \
    curl -fsSL -C- \
    -O http://ftpmirror.gnu.org/emacs/emacs-${emacs_release}.tar.xz \
    -O http://ftpmirror.gnu.org/emacs/emacs-${emacs_release}.tar.xz.sig && \
    tar -xf /tmp/ftp/emacs-${emacs_release}.tar.xz -C / && \
    cd /emacs-${emacs_release} && \
    ./configure \
    --disable-build-details \
    --without-all \
    --without-x \
    --with-gnutls && \
    make -j$(nproc) V=0 CFLAGS='-O2 -pipe' install && \
    rm -r /emacs-${emacs_release}*

ENV PATH=${PATH}:/cask/bin
