name: Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - ci-debug

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '29.4'
          - '30.1'
          # currently broken
          # - 'release-snapshot'
          # - 'snapshot'
        # include:
          # - emacs_version: 'snapshot'
            # allow_failure: true
          # - emacs_version: 'release-snapshot'
            # allow_failure: true
    env:
      - IMAGE: ghcr.io/${{ github.repository_owner }}/devcontainer-test
    steps:
      - uses: actions/checkout@v4
      - name: Pull image
        run: docker pull ${{ env:IMAGE }}:${{ matrix.emacs_version }}
      - name: Cache cask run
        run: docker volume create devcontainer-elpa${{ matrix.emacs_version }}
      - name: test-compile
        run: make test-compile
      - name: test
        run: make test
      - name: checkdoc
        run: make checkdoc
      - name: package-lint
        run: "make package-lint || :"
